export const MAIN_PLAN_ITEMS = [
  {
    key: '1',
    src: '/images/mainPlanPrd1.jpeg',
    width: '215px',
    height: '215px',
    brandName: '클리너리',
    name: '클리너리 오라밸런스 30정 2종 택1',
    OriginPrice: '39,800',
    CurPrice: '32,200',
    flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
  },
  {
    key: '1',
    src: '/images/mainPlanPrd2.jpeg',
    width: '215px',
    height: '215px',
    brandName: '르봉',
    name: '르봉 화이트닝 치약 75g 4종 택 1',
    OriginPrice: '15,900',
    CurPrice: '13,900',
    flagStatus: ['쿠폰', '증정', '오늘드림'],
  },
  {
    key: '2',
    src: '/images/mainPlanPrd3.jpeg',
    width: '215px',
    height: '215px',
    name: '라엘 유기농순면커버 중형/대형/라이너 4팩 3종 택1',
    OriginPrice: '19,000',
    CurPrice: '17,100',
    flagStatus: ['세일'],
  },
  {
    key: '2',
    src: '/images/mainPlanPrd4.jpeg',
    width: '215px',
    height: '215px',
    name: '나트라케어 울트라날개형 생리대 3개입 3종 택1(대/중/소)',
    OriginPrice: '26,100',
    CurPrice: '20,800',
    flagStatus: ['세일'],
  },
  {
    key: '3',
    src: '/images/mainPlanPrd5.jpeg',
    width: '215px',
    height: '215px',
    brandName: '필리밀리',
    name: '[한정기획]필리밀리 듀얼메이크업스파츌라',
    OriginPrice: '12,000',
    CurPrice: '9,800',
    flagStatus: ['세일', '쿠폰', '오늘드림'],
  },
  {
    key: '3',
    src: '/images/mainPlanPrd6.jpeg',
    width: '215px',
    height: '215px',
    brandName: '필리밀리',
    name: '필리밀리 아이브러시 프로 컬렉션(5종)(단품/컬러에디션)',
    OriginPrice: '28,000',
    CurPrice: '21,900',
    flagStatus: ['세일', '쿠폰', '오늘드림'],
  },
  {
    key: '4',
    src: '/images/mainPlanPrd7.jpeg',
    width: '215px',
    height: '215px',
    brandName: '페리페라',
    name: '[말티즈아카이브 콜라보] 페리페라 올테이크 무드라이크팔레트 (스티커 증정)',
    OriginPrice: '28,000',
    CurPrice: '22,400',
    flagStatus: ['세일', '증정', '오늘드림'],
  },
  {
    key: '4',
    src: '/images/mainPlanPrd8.jpeg',
    width: '215px',
    height: '215px',
    brandName: '페리페라',
    name: '[말티즈아카이브 콜라보] 페리페라 잉크 무드 글로이틴트',
    OriginPrice: '12,000',
    CurPrice: '9,600',
    flagStatus: ['세일', '증정', '오늘드림'],
  },
]
