export const MORE_CURATION_ITEMS = [
  {
    src: '/images/prd1.jpeg',
    name: '크리스탈 데오드란트 롤온 66ml',
    width: '160px',
    height: '160px',
    OriginPrice: '13,000',
    CurPrice: '11,700',
    flagStatus: ['세일', '오늘드림'],
  },
  {
    src: '/images/prd2.jpeg',
    name: '그랜즈레미디 오렌지 (신발파우더) 35g',
    width: '160px',
    height: '160px',
    OriginPrice: '19,000',
    CurPrice: '15,200',
    flagStatus: ['세일', '쿠폰', '오늘드림'],
  },
  {
    src: '/images/prd3.jpeg',
    name: '[1등잡티세럼] 아이소이 BR 블레미쉬 케어 업 세럼 더블기획 (20ml+20ml)',
    width: '160px',
    height: '160px',
    OriginPrice: '54,000',
    CurPrice: '39,800',
    flagStatus: ['세일', '오늘드림'],
  },
  {
    src: '/images/prd4.jpeg',
    name: '메이블린뉴욕 래스팅 드라마 젤라이너[블랙/브라운]',
    width: '160px',
    height: '160px',
    CurPrice: '15,000',
    flagStatus: ['세일', '쿠폰', '오늘드림'],
  },

  {
    src: '/images/prd5.jpeg',
    width: '160px',
    height: '160px',
    name: '[7월 올영픽/단독기획] 바닐라코 프라임 프라이머 피니쉬 파우더 12g+ 브러쉬',
    OriginPrice: '22,000',
    CurPrice: '15,800',
    flagStatus: ['세일', '오늘드림'],
  },
  {
    src: '/images/prd6.jpeg',
    width: '160px',
    height: '160px',
    name: '[증량] 쏘피 쿨링 프레쉬 중형20P / 대형 16P 3번들  2종 택1',
    OriginPrice: '21,900',
    CurPrice: '10,830',
    flagStatus: ['세일', '쿠폰', '오늘드림'],
  },
  {
    src: '/images/prd7.jpeg',
    width: '160px',
    height: '160px',
    name: '라로슈포제 에빠끌라 딥클렌징포밍크림 50ml 기획 (+시카 크림 15ml 증정)',
    OriginPrice: '14,000',
    CurPrice: '9,800',
    flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
  },
  {
    src: '/images/prd8.jpeg',
    width: '160px',
    height: '160px',
    name: '[NEW컬러추가] 더샘 커버 퍼펙션 트리플 팟 컨실러 4colors (단품/한정기획)',
    OriginPrice: '12,000',
    CurPrice: '10,800',
    flagStatus: ['세일', '오늘드림'],
  },
  {
    src: '/images/mainPlanPrd1.jpeg',
    width: '160px',
    height: '160px',
    name: '클리너리 오라밸런스 30정 2종 택1',
    OriginPrice: '39,800',
    CurPrice: '32,200',
    flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
  },
  {
    src: '/images/mainPlanPrd2.jpeg',
    width: '160px',
    height: '160px',
    name: '르봉 화이트닝 치약 75g 4종 택 1',
    OriginPrice: '15,900',
    CurPrice: '13,900',
    flagStatus: ['쿠폰', '증정', '오늘드림'],
  },
  {
    src: '/images/mainPlanPrd3.jpeg',
    width: '160px',
    height: '160px',
    name: '라엘 유기농순면커버 중형/대형/라이너 4팩 3종 택1',
    OriginPrice: '19,000',
    CurPrice: '17,100',
    flagStatus: ['세일'],
  },
  {
    src: '/images/mainPlanPrd4.jpeg',
    width: '160px',
    height: '160px',
    name: '나트라케어 울트라날개형 생리대 3개입 3종 택1(대/중/소)',
    OriginPrice: '26,100',
    CurPrice: '20,800',
    flagStatus: ['세일'],
  },
]
