export const BRAND_PRODUCT = [
  {
    key: '1',
    src: '/images/belif_prd1.jpeg',
    name: '빌리프 아쿠아 밤 30ml 라인프렌즈 에코에디션 (+에센스30ml+폼40ml+DIY스티커)',
    width: '100px',
    height: '100px',
    OriginPrice: '29,000',
    CurPrice: '24,600',
    flagStatus: ['세일', '증정', '오늘드림'],
  },
  {
    key: '1',
    src: '/images/belif_prd2.jpeg',
    name: '빌리프 UV프로텍터 톤업 선스크린 50ml 라인프렌즈 에코에디션 (+DIY스티커)',
    width: '100px',
    height: '100px',
    OriginPrice: '39,000',
    CurPrice: '33,100',
    flagStatus: ['세일', '증정', '오늘드림'],
  },
  {
    key: '2',
    src: '/images/studio17_prd1.jpeg',
    name: '[지현서PICK] 스튜디오17 메이크업 브러쉬(18종 중 택1)',
    width: '100px',
    height: '100px',
    CurPrice: '3,800',
    flagStatus: ['오늘드림'],
  },
  {
    key: '2',
    src: '/images/studio17_prd2.jpeg',
    name: '[올댓뮤즈4 한승연 사용]스튜디오17 아이메이크업 브러쉬 세트 (5종)',
    width: '100px',
    height: '100px',
    CurPrice: '12,900',
    flagStatus: ['오늘드림'],
  },
  {
    key: '3',
    src: '/images/naming_prd1.jpeg',
    name: '[재유PICK/증정] 네이밍 매트 핏 쿠션 기획 (쿠션+프라이머 본품 증정)',
    width: '100px',
    height: '100px',
    OriginPrice: '28,000',
    CurPrice: '19,950',
    flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
  },
  {
    key: '3',
    src: '/images/naming_prd2.jpeg',
    name: '[NEW/미니] 네이밍 레이어드 커버 파운데이션 15ml',
    width: '100px',
    height: '100px',
    OriginPrice: '16,000',
    CurPrice: '12,160',
    flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
  },
]
