export const MAINRECOMM_ITEMS = [
  [
    {
      key: '1',
      src: '/images/mainRec1.jpeg',
      brandName: 'AHC',
      width: '215px',
      height: '215px',
      name: '[박세리 공동개발 / 대용량 출시] AHC 마스터즈 에어리치 선스틱 22g',
      OriginPrice: '21,000',
      CurPrice: '13,900',
      flagStatus: ['세일', '쿠폰', '오늘드림'],
    },
    {
      key: '1',
      src: '/images/mainRec2.jpeg',
      width: '215px',
      height: '215px',
      brandName: '에어퀸',
      name: '에어퀸 브레스 유기농 순면 생리대 4종 택1(라이너,생리대,오버나이트)',
      OriginPrice: '5,500',
      CurPrice: '4,400',
      flagStatus: ['쿠폰', '오늘드림'],
    },
    {
      key: '1',
      src: '/images/mainRec3.jpeg',
      width: '215px',
      height: '215px',
      brandName: '러븀',
      name: '[7월 올영PICK / 단독선런칭] 러븀 애프터 글로우 유자 겔 마스크 5매',
      OriginPrice: '25,000',
      CurPrice: '15,750',
      flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
    },
    {
      key: '1',
      src: '/images/mainRec4.jpeg',
      width: '215px',
      height: '215px',
      brandName: '비욘드',
      name: '[7/10하루특가] 비욘드 엔젤아쿠아 수분 진정 크림 150ml 1+1 디즈니 한정기획 (+크림 30ml 증정) ',
      OriginPrice: '25,000',
      CurPrice: '17,400',
      flagStatus: ['세일', '쿠폰', '증정', '오늘드림'],
    },
  ],
  [
    {
      key: '2',
      src: '/images/prd1.jpeg',
      width: '215px',
      height: '215px',
      brandName: '크리스탈',
      name: '크리스탈 데오드란트 롤온 66ml',
      OriginPrice: '13,000',
      CurPrice: '11,700',
      flagStatus: ['세일', '오늘드림'],
    },
    {
      key: '2',
      src: '/images/prd2.jpeg',
      width: '215px',
      height: '215px',
      brandName: '그랜즈레미디',
      name: '그랜즈레미디 오렌지 (신발파우더) 35g',
      OriginPrice: '19,000',
      CurPrice: '15,200',
      flagStatus: ['세일', '쿠폰', '오늘드림'],
    },
    {
      key: '2',
      src: '/images/prd3.jpeg',
      width: '215px',
      height: '215px',
      brandName: '아이소이',
      name: '[1등잡티세럼] 아이소이 BR 블레미쉬 케어 업 세럼 더블기획 (20ml+20ml)',
      OriginPrice: '54,000',
      CurPrice: '39,800',
      flagStatus: ['세일', '오늘드림'],
    },
    {
      key: '2',
      src: '/images/prd4.jpeg',
      width: '215px',
      height: '215px',
      brandName: '메이블린',
      name: '메이블린뉴욕 래스팅 드라마 젤라이너[블랙/브라운]',
      CurPrice: '15,000',
      flagStatus: ['세일', '쿠폰', '오늘드림'],
    },
  ],
]
